// Uygulama genelinde kullanılan renk token'ları. MUI teması (theme.ts) da
// buradaki değerlerden türetilir; renk değiştirmek için tek yer burası.
// Not: Utils.ChangeColorAlpha 6 haneli hex beklediği için değerler hex tutulur.
export const palette = {
  ink: "#0B0D12", // uygulama zemini
  surface: "#12161E", // kart / panel
  surfaceRaised: "#181D27", // hover, seçili satır
  border: "#232938",
  text: "#E7E9EE",
  textMuted: "#8A93A6",
  textFaint: "#5B6478",
  primary: "#FF7849",
  primaryHover: "#F2622F",
  primarySoft: "#FF784926",
  accent: "#22D3EE",
  success: "#22C55E",
  warning: "#F59E0B",
  danger: "#EF4444",
  info: "#3B82F6",
};

export const theme = {
  selected: "default",
  background: palette.ink,
  foreground: "#0F1218",
  foreground_alt: palette.surfaceRaised,
  primary_text: palette.text,
  secondary_text: palette.textMuted,
  link_text: "#FFA585",
  primary: palette.primary,
  secondary: "#64748B",
  alternative: palette.accent,
  danger: palette.danger,
  warning: palette.warning,
  success: palette.success,
  success_alt: "#34D399",
  danger_alt: "#F87171",
  warning_alt: "#FBBF24",
  input_background: "#0F1218",
  input_border: palette.border,
  input_text: "#D7DBE4",
  primary25: "#FF784940",
  primary50: "#FFC9B5",
  primary_dropdown: palette.surfaceRaised,
  neutral0: palette.surface,
  neutral80: "#FFFFFF",
  neutral10: "#0F1218",
  neutral5: palette.surface,
  primary_button: palette.primary,
  primary_button_sub: palette.primaryHover,
  scondary_button: palette.primary,
  button_text: "#FFFFFF",
  button_text_alt: "#FFFFFF",
  table_header: palette.surface,
  table_row_light: palette.surface,
  table_row_dark: "#0F1218",
  error_light: "#2A1215",
  error_text: "#F87171",
  background_light: palette.surface,
};
